#!/usr/bin/env python3

print("Kolejnosc:")
print(2 + 2 * 2)
print((2 + 2) * 2)
print("Dzielenie:")
print(5 / 2)
print(5 // 2)
print("Mnozenie:")
print(2 * 3)
print("Potegowanie:")
print(2**3)
print("Skrocone:")
x = 5
x += 1
print(x)
print("Konwersja typow:")
a = input("Podaj 1 liczbe: ")
b = input("Podaj 2 liczbe: ")
print(a + b)
print(int(a) + int(b))
print(type(a))
c = int(input("Podaj 1 liczbe: "))
d = int(input("Podaj 2 liczbe: "))
print(c + d)
e = input("Podaj 1 liczbe: ")
f = input("Podaj 2 liczbe: ")
print(float(e) + float(f))

g = input("Podaj 1 liczbe: ")
h = input("Podaj 2 liczbe: ")
print(str(g) + str(h))
